import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
         <title>Web & Cloud Solutions | Aaron Riley</title>
                    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
                    <meta name="description" content="Next.js App" />
                    <link rel="icon" href="/logo.svg" />
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
      <head />

      <body class="bg-neutral-900">
        <nav class="bg-neutral-900 border-gray-200 dark:bg-neutral-900">
          <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <a href="#" class="flex items-center mt-5">
              <img src="logo.svg" class="h-8 mr-3" alt="Aaron's Logo" />
            </a>
          </div>
        </nav>
        { children }
      </body>
    </html>
  );
}
